name: Upload KNN-TSPI Package to Pypi on Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    needs: pre-publish
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Update version in __init__.py
        run: >-
          sed -i "s/{{VERSION_PLACEHOLDER}}/$(echo $GITHUB_REF | cut -d / -f 3)/g" knn_tspi/__init__.py
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: "3.10"
          poetry_version: "==1.8.2"
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          plugins: "poetry-dynamic-versioning[plugin]"
