name: Upload KNN-TSPI Package to Pypi on Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make setup-ci
      - name: Lint
        run: make lint-ci
      - name: Test
        run: make test-ci
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Update version in __init__.py
        run: >-
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" __init__.py
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          plugins: "poetry-dynamic-versioning[plugin]"
